export * from "./listsActions";
export * from "./cardsActions";
export * from "./boardActions";

export const CONSTANTS = {
  GET_CARDS: "GET_CARDS",
  ADD_CARD: "ADD_CARD",
  EDIT_CARD_DESC: "EDIT_CARD_DESC",
  EDIT_CARD_NAME: "EDIT_CARD_NAME",
  DELETE_CARD: "DELETE_CARD",
  GET_CARDS_IN_LIST: "GET_CARDS_IN_LIST",
  ADD_LIST: "ADD_LIST",
  GET_LISTS: "GET_LISTS",
  EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
  DELETE_LIST: "DELETE_LIST",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  SET_ACTIVE_BOARD: "SET_ACTIVE_BOARD",
  ADD_BOARD: "ADD_BOARD",
  GET_BOARDS: "GET_BOARDS",
  EDIT_BOARD: "EDIT_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  ADD_COMMENT: "ADD_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
